dual_ubiquitous_display:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  pantilt1_pan_controller:
    type: position_controllers/JointPositionController
    joint: pantilt1_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  pantilt1_tilt_controller:
    type: position_controllers/JointPositionController
    joint: pantilt1_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  pantilt2_pan_controller:
    type: position_controllers/JointPositionController
    joint: pantilt2_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  pantilt2_tilt_controller:
    type: position_controllers/JointPositionController
    joint: pantilt2_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
